/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parse_json_xml;

public class App {

    public static void main(String[] args) {
        System.out.println("Parsing will be here soon");
    }
}
